alembic/versions/e5e9a8a41828_add_new_field_adaptor_properties_hash.py
cads_catalogue/database.py
cads_catalogue/manager.py
tests/data/dumped_resources.txt
tests/data/dumped_resources2.txt
tests/data/dumped_resources3.txt

Reverts ecmwf-projects/cads-catalogue#85

Revert "Revert "Adaptor properties hash""

---

cads_catalogue/config.py
cads_catalogue/database.py
cads_catalogue/faceted_search.py
tests/test_01_config.py
tests/test_02_database.py

according to https://jira.ecmwf.int/browse/COPDS-1323:
* code support for read-only and r&w connection to catalogue database
* all env variables for db connection are now required

Support for read-only and r&w access to the database

---

alembic.ini
alembic/env.py
cads_catalogue/config.py
cads_catalogue/database.py
tests/conftest.py
tests/test_02_database.py

Bug fixed: in case password contains '@': parsing of db connection url fails.

bugfix: right encoding of db connection tokens

---

cads_catalogue/layout_manager.py
cads_catalogue/manager.py
tests/data/dumped_resources1.txt
tests/data/dumped_resources2.txt
tests/test_40_manager.py

See https://jira.ecmwf.int/browse/COPDS-1464

[WIP] qa_flag management

---

cads_catalogue/layout_manager.py
tests/data/cads-forms-cim-json/insitu-gridded-observations-nordic/quality_assurance.layout.json
tests/data/cads-forms-cim-json/insitu-observations-surface-land/quality_assurance.layout.json
tests/data/cads-forms-cim-json/reanalysis-era5-land/quality_assurance.layout.json
tests/test_30_layout_manager.py

Behavior of cads-catalogue management of layout.json has slightly changed according to changes in https://confluence.ecmwf.int/display/CDSM/Web+portal+Quality+Assurance+integration .
Currently it needs also a corresponding change in cads-forms-cim-json

change of cads-catalogue management of layout.json

---

cads_catalogue/layout_manager.py
cads_catalogue/utils.py
tests/test_30_layout_manager.py

it fixes https://github.com/ecmwf-projects/cads-catalogue/issues/111

layout.json processing does not raise errors in case of effective image urls

---

alembic/versions/da7b5a845136_add_override_info.py
cads_catalogue/database.py
cads_catalogue/entry_points.py
cads_catalogue/manager.py
ci/environment-ci.yml
tests/data/dumped_resources7.txt
tests/data/override1.yaml
tests/data/override2.yaml
tests/test_40_manager.py
tests/test_90_entry_points.py

See https://jira.ecmwf.int/browse/COPDS-1465

COPDS-1465: consider a new yaml file to override dataset metadata

---

cads_catalogue/layout_manager.py
tests/test_30_layout_manager.py

Fix https://jira.ecmwf.int/browse/COPDS-1666

COPDS-1666: removal of QA tabs/aside in case of qa_flag is false

---

cads_catalogue/layout_manager.py
tests/data/layout1.json
tests/data/layout2.json
tests/test_30_layout_manager.py

According to https://jira.ecmwf.int/browse/COPDS-2000

new labels during processing licences in layout.json

---

alembic/versions/694fde86c48c_id_manage_of_contents.py
cads_catalogue/contents.py
cads_catalogue/database.py
tests/test_15_contents.py
tests/test_90_entry_points.py

uid of contents stored in the catalogue db are different from each site/application/id property.

different uids for each content's site/application

---

cads_catalogue/config.py
cads_catalogue/database.py

Catalogue engine, called by ensure_session_obj, must be more configurable according to environment variables: pool_size, pool_timeout, max_overflow.

more configurable engine on calling

---

cads_catalogue/contents.py
cads_catalogue/layout_manager.py
cads_catalogue/validations.py
tests/test_30_layout_manager.py

See https://jira.ecmwf.int/browse/COPDS-2384

layout processing for contents

---

cads_catalogue/contents.py
cads_catalogue/entry_points.py

Few things to do and log in case of total skip of the catalogue manager processing

optimize total skip

---

cads_catalogue/contents.py
cads_catalogue/utils.py
tests/data/cads-contents-json/template_config2.yaml
tests/test_01_utils.py
tests/test_15_contents.py
tests/test_90_entry_points.py

See https://jira.ecmwf.int/browse/COPDS-2347

raise in case missing interpolation variables in contents

---

alembic/versions/1f965dd6fb7b_add_priority_for_contents.py
cads_catalogue/contents.py
cads_catalogue/database.py
tests/data/cads-contents-json/copernicus-interactive-climates-atlas/metadata.json
tests/test_15_contents.py

See https://jira.ecmwf.int/browse/COPDS-2439

added priority on contents

---

cads_catalogue/entry_points.py
cads_catalogue/manager.py
cads_catalogue/messages.py
cads_catalogue/repos.py
cads_catalogue/skipping_utils.py
cads_catalogue/utils.py
environment.yml
pyproject.toml
tests/data/repos.yaml
tests/test_01_utils.py
tests/test_04_repos.py
tests/test_90_entry_points.py

See https://jira.ecmwf.int/browse/COPDS-2349

catalogue manager clones input repos

---

README.md
alembic.ini
alembic/env.py
cads_catalogue/alembic_cli.py
cads_catalogue/database.py
pyproject.toml

See https://jira.ecmwf.int/browse/COPDS-2511

Downgrade utility for alembic versions

---

cads_catalogue/database.py
cads_catalogue/entry_points.py
cads_catalogue/repos.py
tests/test_90_entry_points.py

See https://jira.ecmwf.int/browse/COPDS-2551

Store last N sanity checks

---

cads_catalogue/entry_points.py
cads_catalogue/manager.py
cads_catalogue/validations.py

See https://jira.ecmwf.int/browse/COPDS-2641

improve checks

---

alembic/versions/b7bbdaf01165_adding_column_for_sanity_check_.py
cads_catalogue/database.py
cads_catalogue/entry_points.py
cads_catalogue/manager.py
cads_catalogue/sanity_check.py
tests/data/cads-forms-json/reanalysis-era5-single-levels/requests.yaml
tests/data/dumped_resources1.txt
tests/data/dumped_resources2.txt
tests/data/dumped_resources3.txt
tests/data/dumped_resources4.txt
tests/data/dumped_resources5.txt
tests/data/dumped_resources6.txt
tests/data/dumped_resources7.txt
tests/test_40_manager.py

See https://jira.ecmwf.int/browse/COPDS-2779

Copds 2779 ingestion yaml
